import { Injectable, Inject, Logger } from '@nestjs/common';
import type { IVectorStore, IVectorStoreRecord } from '../../../shared-lib/src/interfaces/vector-store.interface';
import { LlmService } from '../../llm/llm.service';
import { MemoryType, MemorySource } from './entities/memory.entity';
import { Worker } from 'worker_threads';
import { join } from 'path';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class MemoryService {
    private readonly logger = new Logger(MemoryService.name);

    private queue: { verify: () => void, task: () => Promise<void> }[] = [];
    private activeWorkers = 0;
    private readonly maxWorkers: number;

    constructor(
        @Inject('IVectorStore')
        private vectorStore: IVectorStore,
        private llmService: LlmService,
        private configService: ConfigService
    ) {
        this.maxWorkers = parseInt(this.configService.get('DISTILLATION_CONCURRENCY') || '4', 10);
    }

    async addMemory(
        userId: string,
        sourceType: MemorySource,
        sourceId: string,
        content: string,
        type: MemoryType = MemoryType.PERSONAL,
        entities: Record<string, any> = {},
        importance: number = 1
    ) {
        try {
            const embedding = await this.llmService.getEmbeddings(content);

            const record: IVectorStoreRecord = {
                id: undefined as any, // ID generated by DB
                content,
                embedding,
                metadata: {
                    userId,
                    sourceType,
                    sourceId,
                    type,
                    entities,
                    importance,
                    tags: []
                }
            };

            await this.vectorStore.add(userId, [record]);
            this.logger.log(`[MemoryService] Added memory for user ${userId}`);
        } catch (error) {
            this.logger.error('Failed to add memory', error);
            throw error;
        }
    }

    async searchMemories(userId: string, query: string, limit: number = 5): Promise<IVectorStoreRecord[]> {
        try {
            const queryEmbedding = await this.llmService.getEmbeddings(query);

            // TODO: Add Keyword Search integration if needed later
            // Currently purely semantic search

            const results = await this.vectorStore.search(userId, queryEmbedding, limit);

            // Re-ranking logic can go here (Recency + Importance formula)
            // Score = (VectorSim * 0.7) + (Importance * 0.2) + (Recency * 0.1)
            // Note: VectorSim is distance-based in pgvector (<=>), so smaller is better. 
            // We need to convert distance to similarity (1 - global_distance) or similar.

            return results;
        } catch (error) {
            this.logger.error('Failed to search memories', error);
            return [];
        }
    }

    async distillConversation(userId: string, sessionId: string, messages: { role: string, content: string }[]) {
        if (messages.length === 0) return;

        // Push to queue
        this.queue.push({
            verify: () => { }, // Placeholder if we need cancellation later
            task: async () => this.runDistillationTask(userId, sessionId, messages)
        });

        this.processQueue();
    }

    private async processQueue() {
        if (this.activeWorkers >= this.maxWorkers) {
            return;
        }

        const item = this.queue.shift();
        if (!item) return;

        this.activeWorkers++;

        // Don't await the task here, let it run in background
        item.task().finally(() => {
            this.activeWorkers--;
            this.processQueue(); // Process next item
        });
    }

    private async runDistillationTask(userId: string, sessionId: string, messages: { role: string, content: string }[]) {
        try {
            const conversationText = messages.map(m => `${m.role}: ${m.content}`).join('\n');
            const prompt = `
Task: Analyze the provided conversation context and distill high-value, long-term memories.
CRITICAL: Do NOT just summarize the conversation events. Instead, extract underlying truths, insights, patterns, and strong opinions.

**CRITICAL ROLE AWARENESS:**
The conversation contains TWO participants:
- "user": The actual user (YOUR PRIMARY FOCUS)
- "assistant": The AI assistant (IGNORE ITS SUGGESTIONS)

RULES:
✅ ONLY extract insights from what the user explicitly said or decided
❌ DO NOT attribute assistant's recommendations to the user
❌ DO NOT create memories like "User thinks X" if only assistant suggested X

Role Confusion Prevention:
If conversation shows:
  assistant: "I recommend using Vercel"
  user: "Okay" (without explicitly agreeing)
→ DO NOT create: "User prefers Vercel"
→ This is assistant's opinion, not user's preference

**CRITICAL DECISION AWARENESS:**
Distinguish between EXPLORATION and CONCLUSION:

EXPLORATION (探索阶段) - Lower priority, avoid if possible:
- "I'm considering A or B" / "我在考虑A或B"
- "What about X?" / "X怎么样？"
- "A has pros, B has cons" / "A有优点，B有缺点"
→ User is still thinking, NO decision made yet

CONCLUSION (决策阶段) - Higher priority, MUST capture:
- "I decided to use X" / "我决定用X"
- "I'll go with Y because..." / "我选择Y，因为..."
- "After considering, I choose Z" / "考虑后，我选Z"
→ User made a final decision, CAPTURE THIS

Signal Words for Decisions (决策信号词):
- Chinese: 决定、选择、确定、最终、采用、用、就用
- English: decided, chosen, will use, going with, settled on, pick

Extraction Priority:
1. HIGHEST: Final decisions with reasoning
2. MEDIUM: Strong preferences ("I prefer X over Y because...")
3. LOWEST: Options being explored ("considering A or B")
4. AVOID: Questions without conclusions

Temporal Priority Rule:
If conversation shows evolution from exploration to decision:
Early: "I'm thinking about A, B, C"
Later: "I decided on B"
→ ONLY extract the final decision (B)
→ IGNORE early exploration phase unless it reveals preference patterns

Focus on extracting:
1. **User Philosophies & Preferences**: The user's deep-seated beliefs about coding, design, or workflow (e.g., "Prefers composition over inheritance", "Strongly dislikes verbose logging", "Values aesthetics over performance"). -> Type: PERSONAL
2. **Technical Insights & Learnings**: Proven solutions or conclusions reached about specific technical problems, including the "Why" (e.g., "WebSockets require heartbeat on mobile due to aggressive OS background suspension"). -> Type: DOMAIN
3. **Project Decisions & Context**: Critical architectural decisions and their rationale. -> Type: TASK

Avoid:
- Trivial facts ("User sent a message about X").
- Transient debugging state ("User is fixing a bug in loop").
- Repetition of logs or error messages.

**Language Rule**: The \`content\` field MUST be in the same language as the User's messages in the verified conversation. If the user speaks Chinese, the memory content MUST be in Chinese. If English, use English.

**Anti-Patterns (禁止的输出形式):**
❌ WRONG: "Firebase提供10GB流量，Vercel提供100GB流量"
   → 纯事实陈述，缺少用户立场

❌ WRONG: "用户询问了关于托管方案的问题"
   → 流程描述，无价值

❌ WRONG: "对话讨论了Firebase和Vercel两种方案的优劣"
   → 摘要式总结

**Correct Patterns (正确的输出形式):**
✅ RIGHT: "用户倾向选择流量充裕的托管方案（重视Vercel 100GB over Firebase 10GB，看重爆款承载能力）"
   → 明确的偏好和决策理由

✅ RIGHT: "用户认为部署速度和图片优化是选择托管方案的关键因素"
   → 提炼出的价值判断

**Golden Rule:** Ask yourself "What did the user DECIDE, PREFER, or LEARN?" not "What did they SAY?"
**黄金准则：** 问自己"用户**决定、偏好或学到了什么**"，而不是"用户**说了什么**"

Output Format: JSON Array of objects.
Allowed Types: "PERSONAL", "TASK", "DOMAIN"

Example with Decision Awareness:

Conversation:
user: "我在纠结用Firebase还是Vercel"
assistant: "Firebase便宜，Vercel功能强"
user: "嗯，流量限制是个问题"
assistant: "是的，Vercel有100GB"
user: "好的，那我就用Vercel了，虽然贵点但流量够"

Correct Output (Decision-focused):
[
  { "content": "用户选择Vercel作为托管方案（权衡后认为流量限制比成本更重要）", "type": "TASK", "importance": 3 },
  { "content": "用户在技术选型时优先考虑可扩展性（流量承载能力）over 成本", "type": "PERSONAL", "importance": 3 }
]

Wrong Outputs to AVOID:
❌ "用户在考虑Firebase和Vercel" (exploration phase, not decision)
❌ "Vercel提供100GB流量" (factual statement from assistant)
❌ "AI建议使用Vercel" (assistant's action, not user's)

Conversation:
${conversationText}

Output JSON (only JSON, no markdown):
`;

            this.logger.log(`[MemoryService] Offloading distillation for session ${sessionId} to Worker Thread... (Active: ${this.activeWorkers}/${this.maxWorkers})`);

            // Worker Thread Execution
            // In NestJS "start:dev" or "start:prod", the code runs from "dist" usually.
            // We expect the worker to be compiled to .js in the same folder.
            const workerPath = join(__dirname, 'distillation.worker.js');

            const config = {
                VERTEX_PROJECT_ID: this.configService.get('VERTEX_PROJECT_ID'),
                VERTEX_LOCATION: this.configService.get('VERTEX_LOCATION'),
                GSA_KEY_FILE: this.configService.get('GSA_KEY_FILE'),
            };

            const runWorker = () => new Promise<any[]>((resolve, reject) => {
                const targetModel = this.configService.get('MEMORY_DISTILLATION_MODEL') || 'gemini-2.0-flash-001';
                const worker = new Worker(workerPath, {
                    workerData: { config, prompt, modelName: targetModel }
                });

                worker.on('message', (msg) => {
                    if (msg.error) {
                        reject(new Error(msg.error));
                    } else {
                        resolve(msg.result);
                    }
                });

                worker.on('error', (err) => {
                    reject(err);
                });

                worker.on('exit', (code) => {
                    if (code !== 0) {
                        reject(new Error(`Worker stopped with exit code ${code}`));
                    }
                });
            });

            let memories: any[] = [];
            try {
                memories = await runWorker();
            } catch (workerError) {
                this.logger.error(`[MemoryService] Worker Logic Failed: ${workerError.message}`);
                throw workerError; // Re-throw to signal failure to caller
            }

            if (!Array.isArray(memories)) return;

            this.logger.log(`[MemoryService] Extracted ${memories.length} memories from session ${sessionId} (via Worker)`);

            for (const m of memories) {
                if (m.content && m.content.length > 5) {
                    // Normalize type to match enum
                    let memoryType = MemoryType.PERSONAL;
                    if (m.type === 'TASK') memoryType = MemoryType.TASK;
                    if (m.type === 'DOMAIN') memoryType = MemoryType.DOMAIN;

                    await this.addMemory(
                        userId,
                        MemorySource.CHAT,
                        sessionId,
                        m.content,
                        memoryType,
                        {}, // entities
                        m.importance || 1
                    );
                }
            }
        } catch (error) {
            this.logger.error(`[MemoryService] Distillation failed for session ${sessionId}:`, error);
            throw error; // Re-throw so caller knows it failed
        }
    }

    /**
     * Recursive Backfill Logic
     * Returns the ID of the last processed message, or null if no messages were processed (caught up).
     */
    async processBackfillChunk(
        userId: string,
        sessionId: string,
        lastProcessedMsgId: string | null,
        messageFetcher: (sessionId: string, lastMsgId: string | null, limit: number) => Promise<{ id: string, role: string, content: string }[]>
    ): Promise<string | null> {
        try {
            // 1. Fetch next chunk
            const limit = parseInt(this.configService.get('DISTILL_BACKFILL_CHUNK_SIZE') || '30', 10);
            const messages = await messageFetcher(sessionId, lastProcessedMsgId, limit);

            if (messages.length === 0) {
                this.logger.debug(`[MemoryService] [Backfill] No more messages to process for ${sessionId}. Backfill Complete.`);
                return null; // Done
            }

            // 2. Distill
            const startId = messages[0].id;
            const endId = messages[messages.length - 1].id;
            this.logger.log(`[MemoryService] [Backfill] Processing chunk for ${sessionId}. Size: ${messages.length}. Range: ${startId} ... ${endId}`);

            await this.runDistillationTask(userId, sessionId, messages); // Re-use existing logic

            // 3. Return checkpoint (last message ID)
            const newCheckpoint = endId;
            this.logger.debug(`[MemoryService] [Backfill] Chunk finished. New Checkpoint: ${newCheckpoint}`);
            return newCheckpoint;
        } catch (error) {
            this.logger.error(`[MemoryService] Backfill chunk failed for session ${sessionId}`, error);
            throw error; // Propagate to retry or fail the job
        }
    }
}
