import { Injectable, Inject, Logger } from '@nestjs/common';
import type { IVectorStore, IVectorStoreRecord } from '../../../shared-lib/src/interfaces/vector-store.interface';
import { LlmService } from '../../llm/llm.service';
import { MemoryType, MemorySource } from './entities/memory.entity';

@Injectable()
export class MemoryService {
    private readonly logger = new Logger(MemoryService.name);

    constructor(
        @Inject('IVectorStore')
        private vectorStore: IVectorStore,
        private llmService: LlmService
    ) { }

    async addMemory(
        userId: string,
        sourceType: MemorySource,
        sourceId: string,
        content: string,
        type: MemoryType = MemoryType.PERSONAL,
        entities: Record<string, any> = {},
        importance: number = 1
    ) {
        try {
            const embedding = await this.llmService.getEmbeddings(content);

            const record: IVectorStoreRecord = {
                id: undefined as any, // ID generated by DB
                content,
                embedding,
                metadata: {
                    userId,
                    sourceType,
                    sourceId,
                    type,
                    entities,
                    importance,
                    tags: []
                }
            };

            await this.vectorStore.add(userId, [record]);
            this.logger.log(`[MemoryService] Added memory for user ${userId}`);
        } catch (error) {
            this.logger.error('Failed to add memory', error);
            throw error;
        }
    }

    async searchMemories(userId: string, query: string, limit: number = 5): Promise<IVectorStoreRecord[]> {
        try {
            const queryEmbedding = await this.llmService.getEmbeddings(query);

            // TODO: Add Keyword Search integration if needed later
            // Currently purely semantic search

            const results = await this.vectorStore.search(userId, queryEmbedding, limit);

            // Re-ranking logic can go here (Recency + Importance formula)
            // Score = (VectorSim * 0.7) + (Importance * 0.2) + (Recency * 0.1)
            // Note: VectorSim is distance-based in pgvector (<=>), so smaller is better. 
            // We need to convert distance to similarity (1 - global_distance) or similar.

            return results;
        } catch (error) {
            this.logger.error('Failed to search memories', error);
            return [];
        }
    }

    async distillConversation(userId: string, sessionId: string, messages: { role: string, content: string }[]) {
        if (messages.length === 0) return;

        try {
            const conversationText = messages.map(m => `${m.role}: ${m.content}`).join('\n');
            const prompt = `
Task: Analyze the following conversation fragment and extract key facts, user preferences, or important context that should be stored as long-term memory for future retrieval.
Focus on:
- User's personal details (name, job, location, relations) -> Type: PERSONAL
- User's strong preferences or dislikes -> Type: PERSONAL
- Specific project details or requirements mentioned -> Type: TASK
- Important decisions made
- Domain knowledge or technical facts -> Type: DOMAIN

Output Format: JSON Array of objects.
Allowed Types: "PERSONAL", "TASK", "DOMAIN"

Example:
[
  { "content": "User is a software engineer working on NestJS", "type": "PERSONAL", "importance": 1 },
  { "content": "Project requires strict TypeScript strict mode", "type": "TASK", "importance": 2 }
]

Conversation:
${conversationText}

Output JSON (only JSON, no markdown):
`;

            const response = await this.llmService.generateContent(prompt);
            // Clean markdown code blocks if present
            const jsonStr = response.replace(/```json/g, '').replace(/```/g, '').trim();

            let memories: any[] = [];
            try {
                memories = JSON.parse(jsonStr);
            } catch (e) {
                this.logger.warn(`[MemoryService] Failed to parse distillation JSON: ${jsonStr}`);
                return;
            }

            if (!Array.isArray(memories)) return;

            this.logger.log(`[MemoryService] Extracted ${memories.length} memories from session ${sessionId}`);

            for (const m of memories) {
                if (m.content && m.content.length > 5) {
                    // Normalize type to match enum
                    let memoryType = MemoryType.PERSONAL;
                    if (m.type === 'TASK') memoryType = MemoryType.TASK;
                    if (m.type === 'DOMAIN') memoryType = MemoryType.DOMAIN;
                    // Default to PERSONAL if unknown (e.g. PREFERENCE)

                    await this.addMemory(
                        userId,
                        MemorySource.CHAT,
                        sessionId,
                        m.content,
                        memoryType,
                        {}, // entities
                        m.importance || 1
                    );
                }
            }
        } catch (error) {
            this.logger.error(`[MemoryService] Distillation failed for session ${sessionId}:`, error);
        }
    }
}
