import { Injectable, Inject, Logger } from '@nestjs/common';
import type { IVectorStore, IVectorStoreRecord } from '../../../shared-lib/src/interfaces/vector-store.interface';
import { LlmService } from '../../llm/llm.service';
import { MemoryType, MemorySource } from './entities/memory.entity';
import { Worker } from 'worker_threads';
import { join } from 'path';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class MemoryService {
    private readonly logger = new Logger(MemoryService.name);

    private queue: { verify: () => void, task: () => Promise<void> }[] = [];
    private activeWorkers = 0;
    private readonly maxWorkers: number;

    constructor(
        @Inject('IVectorStore')
        private vectorStore: IVectorStore,
        private llmService: LlmService,
        private configService: ConfigService
    ) {
        this.maxWorkers = parseInt(this.configService.get('DISTILLATION_CONCURRENCY') || '4', 10);
    }

    async addMemory(
        userId: string,
        sourceType: MemorySource,
        sourceId: string,
        content: string,
        type: MemoryType = MemoryType.PERSONAL,
        entities: Record<string, any> = {},
        importance: number = 1
    ) {
        try {
            const embedding = await this.llmService.getEmbeddings(content);

            const record: IVectorStoreRecord = {
                id: undefined as any, // ID generated by DB
                content,
                embedding,
                metadata: {
                    userId,
                    sourceType,
                    sourceId,
                    type,
                    entities,
                    importance,
                    tags: []
                }
            };

            await this.vectorStore.add(userId, [record]);
            this.logger.log(`[MemoryService] Added memory for user ${userId}`);
        } catch (error) {
            this.logger.error('Failed to add memory', error);
            throw error;
        }
    }

    async searchMemories(userId: string, query: string, limit: number = 5): Promise<IVectorStoreRecord[]> {
        try {
            const queryEmbedding = await this.llmService.getEmbeddings(query);

            // TODO: Add Keyword Search integration if needed later
            // Currently purely semantic search

            const results = await this.vectorStore.search(userId, queryEmbedding, limit);

            // Re-ranking logic can go here (Recency + Importance formula)
            // Score = (VectorSim * 0.7) + (Importance * 0.2) + (Recency * 0.1)
            // Note: VectorSim is distance-based in pgvector (<=>), so smaller is better. 
            // We need to convert distance to similarity (1 - global_distance) or similar.

            return results;
        } catch (error) {
            this.logger.error('Failed to search memories', error);
            return [];
        }
    }

    async distillConversation(userId: string, sessionId: string, messages: { role: string, content: string }[]) {
        if (messages.length === 0) return;

        // Push to queue
        this.queue.push({
            verify: () => { }, // Placeholder if we need cancellation later
            task: async () => this.runDistillationTask(userId, sessionId, messages)
        });

        this.processQueue();
    }

    private async processQueue() {
        if (this.activeWorkers >= this.maxWorkers) {
            return;
        }

        const item = this.queue.shift();
        if (!item) return;

        this.activeWorkers++;

        // Don't await the task here, let it run in background
        item.task().finally(() => {
            this.activeWorkers--;
            this.processQueue(); // Process next item
        });
    }

    private async runDistillationTask(userId: string, sessionId: string, messages: { role: string, content: string }[]) {
        try {
            const conversationText = messages.map(m => `${m.role}: ${m.content}`).join('\n');
            const prompt = `
Task: Analyze the provided conversation context and distill high-value, long-term memories.
CRITICAL: Do NOT just summarize the conversation events. Instead, extract underlying truths, insights, patterns, and strong opinions.

Focus on extracting:
1. **User Philosophies & Preferences**: The user's deep-seated beliefs about coding, design, or workflow (e.g., "Prefers composition over inheritance", "Strongly dislikes verbose logging", "Values aesthetics over performance"). -> Type: PERSONAL
2. **Technical Insights & Learnings**: Proven solutions or conclusions reached about specific technical problems, including the "Why" (e.g., "WebSockets require heartbeat on mobile due to aggressive OS background suspension"). -> Type: DOMAIN
3. **Project Decisions & Context**: Critical architectural decisions and their rationale. -> Type: TASK

Avoid:
- Trivial facts ("User sent a message about X").
- Transient debugging state ("User is fixing a bug in loop").
- Repetition of logs or error messages.

**Language Rule**: The \`content\` field MUST be in the same language as the User's messages in the verified conversation. If the user speaks Chinese, the memory content MUST be in Chinese. If English, use English.

**Anti-Patterns (禁止的输出形式):**
❌ WRONG: "Firebase提供10GB流量，Vercel提供100GB流量"
   → 纯事实陈述，缺少用户立场

❌ WRONG: "用户询问了关于托管方案的问题"
   → 流程描述，无价值

❌ WRONG: "对话讨论了Firebase和Vercel两种方案的优劣"
   → 摘要式总结

**Correct Patterns (正确的输出形式):**
✅ RIGHT: "用户倾向选择流量充裕的托管方案（重视Vercel 100GB over Firebase 10GB，看重爆款承载能力）"
   → 明确的偏好和决策理由

✅ RIGHT: "用户认为部署速度和图片优化是选择托管方案的关键因素"
   → 提炼出的价值判断

**Golden Rule:** Ask yourself "What did the user DECIDE, PREFER, or LEARN?" not "What did they SAY?"
**黄金准则：** 问自己"用户**决定、偏好或学到了什么**"，而不是"用户**说了什么**"

Output Format: JSON Array of objects.
Allowed Types: "PERSONAL", "TASK", "DOMAIN"

Example:
[
  { "content": "用户倾向选择Vercel托管（重视100GB流量和图片优化能力over Firebase）", "type": "PERSONAL", "importance": 3 },
  { "content": "Mobile Safari aggressively suspends WebSocket connections in background tabs, necessitating a robust Ping/Pong heartbeat.", "type": "DOMAIN", "importance": 3 },
  { "content": "The project uses 'file:./' references for shared libraries to simplify CI/CD authentication.", "type": "TASK", "importance": 3 }
]

Conversation:
${conversationText}

Output JSON (only JSON, no markdown):
`;

            this.logger.log(`[MemoryService] Offloading distillation for session ${sessionId} to Worker Thread... (Active: ${this.activeWorkers}/${this.maxWorkers})`);

            // Worker Thread Execution
            // In NestJS "start:dev" or "start:prod", the code runs from "dist" usually.
            // We expect the worker to be compiled to .js in the same folder.
            const workerPath = join(__dirname, 'distillation.worker.js');

            const config = {
                VERTEX_PROJECT_ID: this.configService.get('VERTEX_PROJECT_ID'),
                VERTEX_LOCATION: this.configService.get('VERTEX_LOCATION'),
                GSA_KEY_FILE: this.configService.get('GSA_KEY_FILE'),
            };

            const runWorker = () => new Promise<any[]>((resolve, reject) => {
                const targetModel = this.configService.get('MEMORY_DISTILLATION_MODEL') || 'gemini-2.0-flash-001';
                const worker = new Worker(workerPath, {
                    workerData: { config, prompt, modelName: targetModel }
                });

                worker.on('message', (msg) => {
                    if (msg.error) {
                        reject(new Error(msg.error));
                    } else {
                        resolve(msg.result);
                    }
                });

                worker.on('error', (err) => {
                    reject(err);
                });

                worker.on('exit', (code) => {
                    if (code !== 0) {
                        reject(new Error(`Worker stopped with exit code ${code}`));
                    }
                });
            });

            let memories: any[] = [];
            try {
                memories = await runWorker();
            } catch (workerError) {
                this.logger.error(`[MemoryService] Worker Logic Failed: ${workerError.message}`);
                throw workerError; // Re-throw to signal failure to caller
            }

            if (!Array.isArray(memories)) return;

            this.logger.log(`[MemoryService] Extracted ${memories.length} memories from session ${sessionId} (via Worker)`);

            for (const m of memories) {
                if (m.content && m.content.length > 5) {
                    // Normalize type to match enum
                    let memoryType = MemoryType.PERSONAL;
                    if (m.type === 'TASK') memoryType = MemoryType.TASK;
                    if (m.type === 'DOMAIN') memoryType = MemoryType.DOMAIN;

                    await this.addMemory(
                        userId,
                        MemorySource.CHAT,
                        sessionId,
                        m.content,
                        memoryType,
                        {}, // entities
                        m.importance || 1
                    );
                }
            }
        } catch (error) {
            this.logger.error(`[MemoryService] Distillation failed for session ${sessionId}:`, error);
            throw error; // Re-throw so caller knows it failed
        }
    }

    /**
     * Recursive Backfill Logic
     * Returns the ID of the last processed message, or null if no messages were processed (caught up).
     */
    async processBackfillChunk(
        userId: string,
        sessionId: string,
        lastProcessedMsgId: string | null,
        messageFetcher: (sessionId: string, lastMsgId: string | null, limit: number) => Promise<{ id: string, role: string, content: string }[]>
    ): Promise<string | null> {
        try {
            // 1. Fetch next chunk
            const limit = parseInt(this.configService.get('DISTILL_BACKFILL_CHUNK_SIZE') || '30', 10);
            const messages = await messageFetcher(sessionId, lastProcessedMsgId, limit);

            if (messages.length === 0) {
                this.logger.debug(`[MemoryService] [Backfill] No more messages to process for ${sessionId}. Backfill Complete.`);
                return null; // Done
            }

            // 2. Distill
            const startId = messages[0].id;
            const endId = messages[messages.length - 1].id;
            this.logger.log(`[MemoryService] [Backfill] Processing chunk for ${sessionId}. Size: ${messages.length}. Range: ${startId} ... ${endId}`);

            await this.runDistillationTask(userId, sessionId, messages); // Re-use existing logic

            // 3. Return checkpoint (last message ID)
            const newCheckpoint = endId;
            this.logger.debug(`[MemoryService] [Backfill] Chunk finished. New Checkpoint: ${newCheckpoint}`);
            return newCheckpoint;
        } catch (error) {
            this.logger.error(`[MemoryService] Backfill chunk failed for session ${sessionId}`, error);
            throw error; // Propagate to retry or fail the job
        }
    }
}
